version: '3.7'
services:
  whoami:
    container_name: whoami
    hostname: whoami-svr-7
    image: crpi-p35inr9lrgirg3t0.cn-hangzhou.personal.cr.aliyuncs.com/yaobo-box/whoami:1.0.4
    ports:
      - "802:3000"
    restart: always